name: Test corpus against versions

on: [push,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
#         python-version: [2.7, 3.5, 3.6, 3.7]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@master
    - uses: actions/checkout@master
      with:
        repository: apache/incubator-ponymail
        path: ponymail-0.10
        ref: refs/tags/0.10
    - uses: actions/checkout@master
      with:
        repository: apache/incubator-ponymail
        path: ponymail-0.11
        ref: refs/tags/0.11
    - uses: actions/checkout@master
      with:
        repository: apache/incubator-ponymail
        path: ponymail
    - uses: actions/checkout@master
      with:
        repository: apache/incubator-ponymail-foal
        path: ponymail-foal
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ponymail 0.11 Init
      run: |
        cd ponymail-0.11
        sed -e 's/# cropout:/cropout:/' tools/ponymail.cfg.sample >tools/ponymail.cfg
    - name: Ponymail 0.11 Test main
      run: |
        PYTHONHASHSEED=0 python runall.py --root ponymail-0.11
    - name: Ponymail init
      run: |
        cd ponymail
        sed -e 's/# cropout:/cropout:/' tools/ponymail.cfg.sample >tools/ponymail.cfg
    - name: Ponymail Test main
      run: |
        python runall.py --root ponymail
    - name: Foal init
      run: |
        cd ponymail-foal
        sed -e 's/# cropout:/cropout:/' tools/ponymail.yaml.example >tools/ponymail.yaml
    - name: Foal Test main
      run: |
        python runall.py --root ponymail-foal
    - name: Ponymail 0.10 init
      run: |
        cd ponymail-0.10
        sed -e 's/#cropout:.*/cropout:                (\\w+\\.\\w+)\\.incubator\\.apache\\.org \\1.apache.org/' tools/ponymail.cfg.sample >tools/ponymail.cfg
    - name: Ponymail 0.10 Test main
      run: |
        PYTHONHASHSEED=0 python runall.py --root ponymail-0.10
